config/routes.rb
Rails.application.routes.draw do

  resources :records, only:[:index, :create, :new, :edit, :destroy, :update] do
  collection do
    post :confirm 
  end
end
  
  root 'top#index'
  
end

app/models/record.rb
class Record < ActiveRecord::Base
  validates :content, length: { maximum: 255 }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  
  before_action :set_record,  only: [:edit, :update, :destroy]
  
  def index
    @records = Record.all
  end
  
  def new
    if params[:back]
      @record = Record.new(records_params)
    else
      @record = Record.new
  end
end
  
  def create
    @record = Record.new(records_params)
    if @record.save
      redirect_to records_path,notice:"投稿しました。消すなら人目につかないうちに…"
    else
      render 'new'
    end
  end
  
  def confirm
    @record = Record.new(records_params)
    render 'new' if @record.invalid?
  end
  
  def edit
    set_record
  end
  
  def update
    set_record
    if
    @record.update(records_params)
    redirect_to records_path,notice:"編集しました!!"
  else
    render 'new'
  end
 end
  
  def destroy
    set_record
    @record.destroy
    redirect_to records_path,notice:"本当に消しちゃいましたよ(´・ω・`)"
  end
  
  private
  def records_params
    params.require(:record).permit(:content, :edit,)
  end
  
  def set_record
    @record = Record.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clone_helper.rb
module CloneHelper
end

app/helpers/records_helper.rb
module RecordsHelper
    def chosen_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
        confirm_records_path
    else
        record_path
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/clone/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<h1>Clone#index</h1>
<p>Find me in app/views/clone/index.html.erb</p>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Twitterに似た何か</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<header>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "HOME", root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
          	<li><%= link_to "ツブヤク", new_record_path %></li>
            <li><%= link_to "ツイート一覧", records_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

<%= yield %>

<footer>
  学習用ページ
</footer>

</body>
</html>

app/views/records/_form.html.erb
<div class="container">
<div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

<p id="notice"><%= notice %></p>

<%= form_for(@record, url:chosen_new_or_edit) do |f| %>
  <% if @record.errors.any? %>
  <div id = "error_explanation">
  <h2><%= @record.errors.count %>件のエラーがあります</h2>
  <ul>
　<% @record.errors.full_messages.each do |msg| %>
　<li><%= msg %></li>
<% end %>
  </ul>
  </div>
 <% end %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit'登録', class: 'btn btn-primary btn-block' %>
<% end %> 
<br>
<%= link_to"一覧へ",records_path %>
</div>
</div>

app/views/records/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

<h3>以下の内容で送信します</h3>

<%= form_for(@record) do |f| %>
<%= f.hidden_field:content %>

<p>内容:<%= @record.content %></p>
<%= f.submit"登録する", class: 'btn btn-primary btn-block' %>
<% end %>

<%= form_for(@record, url:new_record_path, method: 'get') do |f| %>
<%= f.hidden_field :content %>
<% end %>

<br>
<%= form_for(@record, url:new_record_path, method: 'get') do |f| %>
<%= f.hidden_field :content %>
<%= f.submit'戻る', name: 'back',class: 'btn btn-default btn-block' %>
<% end %>

</div>
</div>

app/views/records/edit.html.erb
<h1>編集する</h1>

<%= render 'form' %>

app/views/records/index.html.erb
<div class="container">
 <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
<p id ="notice"><%= notice %></p>
<h1>つぶやき一覧</h1>
 <%= link_to "ツブヤク", new_record_path %>
<% @records.each do |record| %>
<div class="row">
 <h4><strong><%= record.content %></strong></h4>
<%= link_to "編集",edit_record_path(record.id), class: 'btn btn-success'%>
<%= link_to "消す",record_path(record.id),method: :delete, data: {confirm:'本当に削除してよろしいですか？'},class: 'btn btn-danger' %>
</div>
<% end %>
<div id = "page-top-btn" class = "page-top-btn">
    <p><a class = "move-page-top" id = "move-page-top">▲</a></p>
</div>
</div>
</div>

app/views/records/new.html.erb
<h1>今、何してる？</h1>
<%= render 'form' %>

app/views/top/index.html.erb
<section class="about">
  <h1>About This Page</h1>
  <p>
     Twitterを模倣した何かです
  </p>
</section>